### PR TITLE
Agelesspartners

### PR DESCRIPTION
**Pull request by agelesspartners**
Ensure correct documents are up to date like README.

### CODE REVIEW

**Comment by mikepsinn** [comment]
Also, we should probably name the pull requests to describe what's in them.  

And you can add your git script to the .gitignore:
 https://github.com/cure-dao/draft-whitepaper/pull/199/files#diff-ae2fbe20e24142cf7dafd79a7d301a6fdb89344f0f767f8141d3d86ee5f27d42 

That's specific to you and shouldn't be in everyone's repos.

**Comment by agelesspartners** [comment]
> Also, we should probably name the pull requests to describe what's in them.
> 
> And you can add your git script to the .gitignore: https://github.com/cure-dao/draft-whitepaper/pull/199/files#diff-ae2fbe20e24142cf7dafd79a7d301a6fdb89344f0f767f8141d3d86ee5f27d42
> 
> That's specific to you and shouldn't be in everyone's repos.

Sounds good. I've removed the autogit.sh file by adding it to the gitignore. Thank you.

**Comment by agelesspartners** [comment]
> @agelesspartners Thanks for putting this in the repo!
> 
> Would you mind separating it into separate files? This is a lot of text to expect someone to read when immediately joining.
> 
> For instance, we could create a new Code of Conduct on a separate page and just link to:
> 
> https://github.com/cure-dao/draft-whitepaper/blob/f4294af2ef65958974ff75b37c0e52ff68ecee8e/how-to/onboarding.md?plain=1#L111
> 
> With How to Get Involved, can we just link to that existing page at https://docs.curedao.org/how-to? Then we only have to remember to update it in one place. That's helpful because it's evolving all the time so we'll never be able to remember to update it everywhere.

I could break the onboarding file into separate sections. @vincenzodomina any thoughts?

Also, I wasn't sure on the second step there. Thanks!

**Comment by vincenzodomina** [comment]
@agelesspartners yeah sounds good, go ahead

**Comment by agelesspartners** [comment]
> > @agelesspartners Thanks for putting this in the repo!
> > Would you mind separating it into separate files? This is a lot of text to expect someone to read when immediately joining.
> > For instance, we could create a new Code of Conduct on a separate page and just link to:
> > https://github.com/cure-dao/draft-whitepaper/blob/f4294af2ef65958974ff75b37c0e52ff68ecee8e/how-to/onboarding.md?plain=1#L111
> > 
> > With How to Get Involved, can we just link to that existing page at https://docs.curedao.org/how-to? Then we only have to remember to update it in one place. That's helpful because it's evolving all the time so we'll never be able to remember to update it everywhere.
> 
> I could break the onboarding file into separate sections. @vincenzodomina any thoughts?
> 
> Also, I wasn't sure on the second step there. Thanks!

I broke it up into separate parts on GitHub. Hope that works! :)

**Comment by mikepsinn** [comment]
Thanks, @agelesspartners ! :D

**Review by mikepsinn — APPROVED** [review]

**Pull request merged**
